#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "is kill"
    exit 1
fi

# can be 'release', 'fastdebug', 'slowdebug'
if [ -z "$2" ]; then
    TYPE=${TYPE:-'release'}
else
    TYPE=${TYPE:-"$2"}
fi

DIR="build/linux-x86_64-normal-server-$TYPE"
IMG="j2sdk-image.java8.$1"

if [ -d "$IMG" ]; then
    echo "Local image $IMG exists"
    rm -rf "$IMG"
fi

if [ -d "$HOME/jvms/$IMG" ]; then
    echo "Image $IMG in ~/jvms/ exists"
    rm -rf "$HOME/jvms/$IMG"
fi

cp -r "$DIR"/jdk/objs/java_objs/java.debuginfo "$DIR"/images/j2sdk-image/bin/

if [ "$3" == "debuginfo" ]; then
    pushd "$DIR"/images/j2sdk-image/jre/lib/amd64/server
    unzip -o libjvm.diz
    popd
fi

JAVA_HOME="$DIR/images/j2sdk-image"

if [ "$4" == "forkjvm" ]; then
    if [[ ! -d $JAVA_HOME/forkjvm ]]; then
        mkdir $JAVA_HOME/forkjvm
        mkdir $JAVA_HOME/forkjvm/data
        mkdir $JAVA_HOME/forkjvm/static_analysis
    fi

    # client
    mv $JAVA_HOME/bin/java $JAVA_HOME/bin/java_real
    cp $HOME/forkjvm/jvmperf_openjdk8u/forkjvm/client/java $JAVA_HOME/bin

    # sa
    cp $HOME/forkjvm/jvmperf_openjdk8u/forkjvm/static_analysis/build/* $JAVA_HOME/forkjvm/static_analysis
fi

cp -r "$DIR"/images/j2sdk-image "$IMG"

if [[ -d $HOME/jvms ]]; then
    cp -r "$DIR"/images/j2sdk-image "$HOME/jvms/$IMG"

    if [[ -e $HOME/jvms/java_home ]]; then
        rm $HOME/jvms/java_home
    fi
    ln -s  "$HOME/jvms/$IMG" "$HOME/jvms/java_home"
fi
