#!/usr/bin/env bash

FORKJVM_DATA="$JAVA_HOME/forkjvm/data"
if [ ! -d "$FORKJVM_DATA" ]; then
    echo "ForkJVM data not found in $FORKJVM_DATA"
    exit 1
fi

for d in "$FORKJVM_DATA"/*; do
    if [ -d "$d" ]; then
        echo "ForkJVM: dir $d..."
        PIDFILE="$d/pid.txt"
        if [ -f "$PIDFILE" ]; then
            PID="$(< "$PIDFILE")"
            echo "ForkJVM: sending sigterm to $PID"
            kill "$PID"
            sleep 3
            if kill -s 0 "$PID" 2> /dev/null; then
                echo "ForkJVM: killing $PID"
                kill -9 "$PID"
            else
                echo "ForkJVM: pid $PID terminated successfully"
            fi
        fi
        rm -r "$d"
    fi
done
